-- TOTAL: 18 entries

INSERT INTO items (owner_id, title, quantity, price_per_item, description, picture_url, posted_at, sold, active)
VALUES

(3, 'Bulbasaur', 1, 1000, 'There is a plant seed on its back right from the day this Pokémon is born. The seed slowly grows larger.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png',  '01/10/2021', FALSE, TRUE),
(4, 'Charmander', 1, 33333, 'It has a preference for hot things. When it rains, steam is said to spout from the tip of its tail', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/004.png',  '01/11/2021', FALSE, TRUE),
(5, 'Squirtle', 1, 4444, 'When it retracts its long neck into its shell, it squirts out water with vigorous force.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/007.png',  '01/12/2021', FALSE, TRUE),
(2, 'Caterpie', 1, 16369, 'For protection, it releases a horrible stench from the antenna on its head to drive away enemies.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/010.png',  '01/13/2021', FALSE, TRUE),
(3, 'Chikorita', 1, 18091, 'In battle, Chikorita waves its leaf around to keep the foe at bay. However, a sweet fragrance also wafts from the leaf, becalming the battling Pokémon and creating a cozy, friendly atmosphere all around', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/152.png',  '01/14/2021', FALSE, TRUE),
(4, 'Ekans', 1, 19813, 'The older it gets, the longer it grows. At night, it wraps its long body around tree branches to rest.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/023.png',  '01/15/2021', FALSE, TRUE),
(2, 'Abra', 1, 21535, 'This Pokémon uses its psychic powers while it sleeps. The contents of Abra’s dreams affect the powers that the Pokémon wields.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/063.png',  '01/16/2021', FALSE, TRUE),
(4, 'Jigglypuff', 1, 23257, 'Jigglypuff has top-notch lung capacity, even by comparison to other Pokémon. It won’t stop singing its lullabies until its foes fall asleep.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/039.png',  '01/17/2021', FALSE, TRUE),
(5, 'Diglett', 1, 24979, 'If a Diglett digs through a field, it leaves the soil perfectly tilled and ideal for planting crops.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/050.png',  '01/18/2021', FALSE, TRUE),
(6, 'Lickitung', 1, 26701, 'If this Pokémon’s sticky saliva gets on you and you don’t clean it off, an intense itch will set in. The itch won’t go away, either.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/108.png',  '01/19/2021', FALSE, TRUE),
(2, 'Slowpoke', 2, 20000, 'Slow-witted and oblivious, this Pokémon won’t feel any pain if its tail gets eaten. It won’t notice when its tail grows back, either.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/079.png',  '01/20/2021', TRUE, FALSE),
(3, 'Chansey', 1, 15000, 'The egg Chansey carries is not only delicious but also packed with nutrition. It’s used as a high-class cooking ingredient.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/113.png',  '01/21/2021', FALSE, TRUE),
(1, 'Ditto', 1, 10000, 'It can reconstitute its entire cellular structure to change into what it sees, but it returns to normal when it relaxes.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/132.png',  '01/22/2021', FALSE, TRUE),
(2, 'Snorlax', 1, 5000, 'It is not satisfied unless it eats over 880 pounds of food every day. When it is done eating, it goes promptly to sleep.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/143.png',  '01/23/2021', FALSE, TRUE),
(4, 'Mew', 1, 11000, 'When viewed through a microscope, this Pokémon’s short, fine, delicate hair can be seen', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/151.png',  '01/24/2021', FALSE, TRUE),
(2, 'Furret', 1, 8000, 'Furret has a very slim build. When under attack, it can slickly squirm through narrow spaces and get away. In spite of its short limbs, this Pokémon is very nimble and fleet.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/162.png',  '01/25/2021', FALSE, TRUE),
(3, 'Igglybuff', 3, 10000, 'Igglybuff loves to sing. Its marshmallow-like body gives off a faint sweet smell.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/174.png',  '01/26/2021', FALSE, TRUE),
(4, 'Skitty', 1, 20000, 'Skitty has the habit of becoming fascinated by moving objects and chasing them around. This Pokémon is known to chase after its own tail and become dizzy.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/300.png',  '01/27/2021', FALSE, TRUE),
(6, 'Porygon', 1, 9999, 'State-of-the-art technology was used to create Porygon. It was the first artificial Pokémon to be created via computer programming.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/137.png',  '01/28/2021', FALSE, TRUE),
(7, 'Porygon2', 2, 8888, 'This is a Porygon that was updated with special data. Porygon2 develops itself by learning about many different subjects all on its own.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/233.png',  '01/29/2021', FALSE, TRUE),
(8, 'PorygonZ', 3, 7777, 'Porygon-Z had a program installed to allow it to move between dimensions, but the program also caused instability in Porygon-Z’s behavior.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/474.png',  '01/30/2021', FALSE , TRUE),
(1, 'Cyndaquil', 1, 6578, 'Cyndaquil protects itself by flaring up the flames on its back. The flames are vigorous if the Pokémon is angry. However, if it is tired, the flames splutter fitfully with incomplete combustion.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/155.png',  '01/31/2021', FALSE, TRUE),
(2, 'Gyarados', 1, 6969, 'It has an extremely aggressive nature. The Hyper Beam it shoots from its mouth totally incinerates all targets.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/130.png',  '02/01/2021', FALSE, TRUE),
(5, 'Magikarp', 55, 100, 'It is virtually worthless in terms of both power and speed. It is the most weak and pathetic Pokémon in the world.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/129.png',  '02/02/2021', FALSE, TRUE),
(9, 'Gengar', 1, 9000, 'On the night of a full moon, if shadows move on their own and laugh, it must be Gengar’s doing.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/094.png',  '02/03/2021', FALSE, TRUE),
(3, 'Dugtrio', 2, 1000, 'A team of Diglett triplets. It triggers huge earthquakes by burrowing 60 miles underground.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/051.png',  '02/04/2021', FALSE, TRUE),
(9, 'Rayquaza', 1, 99999, 'Rayquaza is said to have lived for hundreds of millions of years. Legends remain of how it put to rest the clash between Kyogre and Groudon.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/384.png',  '02/05/2021', FALSE, TRUE);
