DROP TABLE IF EXISTS items CASCADE;

CREATE TABLE items (
  id SERIAL PRIMARY KEY NOT NULL,
  owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  quantity SMALLINT NOT NULL,
  price_per_item INTEGER NOT NULL DEFAULT 0,
  description TEXT NOT NULL,
  picture_url VARCHAR(255) NOT NULL,
  posted_at TIMESTAMP NOT NULL,
  sold BOOLEAN NOT NULL DEFAULT FALSE,
  sold_date TIMESTAMP,
  active BOOLEAN NOT NULL DEFAULT TRUE
);
